# Generated by Django 5.2.13 on 2026-05-01 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=100, unique=True)),
                ('court', models.CharField(max_length=200)),
                ('bench', models.CharField(blank=True, max_length=300)),
                ('petitioner', models.TextField()),
                ('respondent', models.TextField()),
                ('case_type', models.CharField(max_length=50)),
                ('judgment_date', models.DateField()),
                ('pdf_file', models.FileField(upload_to='judgments/')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('extracted', 'Extracted'), ('review_pending', 'Review Pending'), ('verified', 'Verified'), ('action_created', 'Action Plan Created')], default='uploaded', max_length=30)),
                ('ocr_confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_data', models.JSONField(default=dict)),
                ('operative_order', models.TextField()),
                ('court_directions', models.JSONField(default=list)),
                ('order_type', models.CharField(max_length=50)),
                ('entities', models.JSONField(default=list)),
                ('extraction_confidence', models.FloatField(default=0.0)),
                ('source_references', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_data', to='cases.case')),
            ],
        ),
    ]
