# Generated by Django 5.2.13 on 2026-05-05 21:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matter_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Groups trial court + HC appeal + SC appeal together')),
                ('cnr_number', models.CharField(blank=True, help_text='16-digit eCourts Case Record Number', max_length=20, null=True, unique=True)),
                ('court_name', models.CharField(max_length=200)),
                ('case_type', models.CharField(max_length=100)),
                ('case_number', models.CharField(max_length=50)),
                ('case_year', models.IntegerField()),
                ('petitioner_name', models.TextField()),
                ('respondent_name', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('disposed', 'Disposed')], default='pending', max_length=20)),
                ('area_of_law', models.CharField(blank=True, max_length=100)),
                ('primary_statute', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appealed_from_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals', to='cases.case')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('court_name', 'case_number', 'case_year')},
            },
        ),
        migrations.CreateModel(
            name='Judgment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_order', models.DateField()),
                ('document_type', models.CharField(default='Final Judgment', help_text='Final Judgment, Interim Stay, Notice, etc.', max_length=50)),
                ('presiding_judges', models.JSONField(default=list)),
                ('disposition', models.CharField(blank=True, help_text='Allowed, Dismissed, Partly Allowed, Remanded', max_length=30)),
                ('winning_party_type', models.CharField(blank=True, help_text='Petitioner, Respondent', max_length=30)),
                ('operative_order_text', models.TextField(blank=True)),
                ('summary_of_facts', models.TextField(blank=True)),
                ('issues_framed', models.JSONField(default=list)),
                ('ratio_decidendi', models.TextField(blank=True, help_text="Judge's legal reasoning / analysis")),
                ('court_directions', models.JSONField(default=list)),
                ('raw_extracted_json', models.JSONField(default=dict)),
                ('entities', models.JSONField(default=list)),
                ('contempt_indicators', models.JSONField(default=list)),
                ('contempt_risk', models.CharField(default='Low', help_text='High, Medium, Low', max_length=20)),
                ('financial_implications', models.JSONField(default=dict)),
                ('appeal_type', models.CharField(blank=True, default='none', max_length=30)),
                ('extraction_confidence', models.FloatField(default=0.0)),
                ('ocr_confidence', models.FloatField(blank=True, null=True)),
                ('pdf_file', models.FileField(upload_to='judgments/')),
                ('pdf_storage_url', models.URLField(blank=True)),
                ('processing_status', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsing', 'Parsing PDF'), ('extracting', 'LLM Extracting'), ('vectorizing', 'Vectorizing'), ('complete', 'Complete'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judgments', to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cited_case_name_raw', models.CharField(max_length=500)),
                ('citation_id_raw', models.CharField(blank=True, help_text='e.g. (2010) 5 SCC 186', max_length=200)),
                ('citation_context', models.CharField(blank=True, help_text='Relied upon, Distinguished, Overruled, Referred', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cited_case', models.ForeignKey(blank=True, help_text='NULL = ghost node (case not yet in DB)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_citations', to='cases.case')),
                ('citing_judgment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_citations', to='cases.judgment')),
            ],
        ),
    ]
