# Generated by Django 5.2.13 on 2026-05-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='principle_extracted',
            field=models.TextField(blank=True, help_text='The legal principle for which this case was cited'),
        ),
        migrations.AddField(
            model_name='judgment',
            name='precedent_status',
            field=models.CharField(choices=[('good_law', 'Good Law'), ('reversed', 'Reversed'), ('modified', 'Modified'), ('overruled', 'Overruled'), ('unknown', 'Unknown')], default='good_law', help_text='Whether this judgment is still valid law for precedent use', max_length=20),
        ),
        migrations.AlterField(
            model_name='citation',
            name='citation_context',
            field=models.CharField(blank=True, choices=[('Relied upon', 'Relied upon'), ('Distinguished', 'Distinguished'), ('Overruled', 'Overruled'), ('Referred', 'Referred')], help_text='How the citing court used this precedent', max_length=30),
        ),
    ]
