# Generated by Django 5.2.13 on 2026-05-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_citation_principle_extracted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_number',
            field=models.CharField(max_length=255),
        ),
    ]
