# Generated by Django 5.2.13 on 2026-05-13 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_department_alter_user_role_alter_user_department'),
        ('cases', '0003_alter_case_case_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='primary_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_cases', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='case',
            name='secondary_departments',
            field=models.ManyToManyField(blank=True, related_name='secondary_cases', to='accounts.department'),
        ),
    ]
