# Generated by Django 5.2.13 on 2026-05-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_case_primary_department_case_secondary_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgment',
            name='pdf_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 of the uploaded PDF; used for dedup on extract.', max_length=64),
        ),
    ]
