services:
  - type: web
    name: nyaya-drishti-api
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn config.wsgi --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: NVIDIA_API_KEY
        sync: false
      - key: NVIDIA_BASE_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_BASE_URL
        sync: false
      - key: LLM_PROVIDER
        sync: false
