import React from 'react';
import { motion } from 'motion/react';
import { CaseData } from '../api/client';

const DetailItem = ({ label, value }: { label: string; value: string }) => (
  <div className="flex flex-col gap-2">
    <span className="text-on-surface-variant text-[10px] font-bold uppercase tracking-[0.15em] border-b border-outline-variant/10 pb-2">
      {label}
    </span>
    <span className="text-on-surface font-semibold text-lg tracking-tight">
      {value}
    </span>
  </div>
);

const getDepartmentColors = (source: string) => {
  const s = source.toLowerCase();
  if (s.includes('pollution') || s.includes('kspcb')) return 'bg-green-500/10 border-green-500/30 text-green-400';
  if (s.includes('revenue') || s.includes('tax')) return 'bg-amber-400/10 border-amber-400/30 text-amber-400';
  if (s.includes('labor') || s.includes('hr')) return 'bg-purple-500/10 border-purple-500/30 text-purple-400';
  if (s.includes('legal')) return 'bg-primary-blue/10 border-primary-blue/30 text-primary-blue';
  return 'bg-surface-container-high/50 border-outline-variant/30 text-on-surface-variant';
};

export const CaseOverview = ({ caseData, verifiedActions, onGoToVerify }: { caseData?: CaseData | null, verifiedActions?: any[], onGoToVerify?: () => void }) => {
  const judgment = caseData?.judgments?.[0];
  const filingDate = caseData?.created_at
    ? new Date(caseData.created_at).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })
    : '—';
  const summaryText = judgment?.summary_of_facts || judgment?.operative_order_text || 'No case brief extracted yet.';
  const contemptRisk = judgment?.contempt_risk || 'Low';
  const citations = judgment?.outgoing_citations ?? [];
  const isVerified = verifiedActions && verifiedActions.length > 0 && verifiedActions.every(a => a.isVerified);

  return (
    <div className="grid grid-cols-1 xl:grid-cols-12 gap-8 py-8">
      {/* Left Column */}
      <div className="xl:col-span-7 space-y-8">
        
        {/* Case Details Card */}
        <div className="glass-card p-6">
          <div className="flex items-center gap-4 mb-8">
            <div className="bg-secondary-container/40 p-2.5 rounded-lg border border-outline-variant/20">
              <span className="material-symbols-outlined text-primary-blue">description</span>
            </div>
            <h4 className="font-bold text-on-surface text-xl tracking-tight">Case Details</h4>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-10">
            <DetailItem label="Jurisdiction" value={caseData?.court_name || '—'} />
            <DetailItem label="Filing Date" value={filingDate} />
            <DetailItem label="Case Type" value={caseData?.case_type || '—'} />
          </div>
        </div>

        {/* Executive Case Brief Card */}
        <div className="glass-card p-8 border-l-4 border-l-primary-blue relative overflow-hidden group">
          <div className="absolute -right-20 -top-20 w-48 h-48 bg-primary-blue/5 blur-[100px] group-hover:bg-primary-blue/10 transition-all duration-500"></div>
          
          <div className="flex items-start justify-between mb-6">
            <div>
              <h3 className="text-on-surface text-2xl font-bold tracking-tight mb-1">Executive Case Brief</h3>
              <p className="text-on-surface-variant text-xs font-medium tracking-wider uppercase opacity-70">
                Generated by Drishti-V4 Legal Engine
              </p>
            </div>
            <div className="bg-primary-blue/10 p-3 rounded-xl border border-primary-blue/20">
              <span className="material-symbols-outlined text-primary-blue text-2xl">auto_awesome</span>
            </div>
          </div>
          
          <p className="text-on-surface/90 leading-relaxed text-base font-medium">
            {summaryText}
          </p>
        </div>

        {/* AI Recommendation Card */}
        <div className="glass-card flex flex-col md:flex-row items-start md:items-center gap-8 p-8 border border-primary-blue/10">
          <div className="w-16 h-16 rounded-full bg-primary-blue/10 border border-primary-blue/20 flex items-center justify-center flex-shrink-0">
            <span className="material-symbols-outlined text-primary-blue text-4xl">smart_toy</span>
          </div>
          <div className="flex-grow">
            <div className="flex flex-wrap items-center gap-4 mb-3">
              <h2 className="text-on-surface text-xl font-bold tracking-tight">
                AI Recommendation: <span className="text-primary-blue">{judgment?.disposition || 'REVIEW'}</span>
              </h2>
              <div className={`flex items-center gap-2 px-3 py-1 rounded-full ${
                contemptRisk === 'High' ? 'bg-error-red/10 border border-error-red/20' :
                contemptRisk === 'Medium' ? 'bg-amber-400/10 border border-amber-400/20' :
                'bg-green-500/10 border border-green-500/20'
              }`}>
                <span className={`material-symbols-outlined text-sm ${
                  contemptRisk === 'High' ? 'text-error-red' : contemptRisk === 'Medium' ? 'text-amber-400' : 'text-green-400'
                }`}>warning</span>
                <span className={`text-[10px] font-bold uppercase tracking-widest ${
                  contemptRisk === 'High' ? 'text-error-red' : contemptRisk === 'Medium' ? 'text-amber-400' : 'text-green-400'
                }`}>
                  Contempt Risk: {contemptRisk}
                </span>
              </div>
            </div>
            <p className="text-on-surface-variant text-sm leading-relaxed font-medium">
              {judgment?.ratio_decidendi || 'Analysis pending. Complete extraction to generate AI recommendation.'}
            </p>
          </div>
        </div>

        {/* Verification Alert Card - Only show if not verified */}
        {!isVerified && (
          <div className="bg-surface-container-highest/20 border border-outline-variant/30 rounded-2xl p-6 flex flex-col md:flex-row items-center justify-between gap-6">
            <div className="flex items-start gap-4">
              <span className="material-symbols-outlined text-primary-blue mt-1">info</span>
              <div>
                <p className="text-on-surface font-bold text-lg tracking-tight mb-1 uppercase text-sm">Verification Required</p>
                <p className="text-on-surface-variant text-sm">
                  You must verify compliance actions generated before you can comply/choose to appeal.
                </p>
              </div>
            </div>
            <button 
              onClick={onGoToVerify}
              className="whitespace-nowrap px-8 py-3.5 bg-primary-blue text-on-primary-blue font-bold rounded-xl flex items-center gap-3 shadow-[0_0_20px_rgba(173,198,255,0.2)] hover:shadow-[0_0_30px_rgba(173,198,255,0.4)] transition-all transform hover:-translate-y-0.5"
            >
              <span className="material-symbols-outlined">verified</span>
              Verify Action Plan
            </button>
          </div>
        )}

        {/* Verified Status Card - Show when verified */}
        {isVerified && (
          <div className="bg-green-500/10 border border-green-500/20 rounded-2xl p-6 flex items-center gap-4">
            <div className="w-12 h-12 rounded-full bg-green-500/20 flex items-center justify-center">
              <span className="material-symbols-outlined text-green-400">task_alt</span>
            </div>
            <div>
              <p className="text-green-400 font-bold text-lg tracking-tight">Compliance Plan Verified</p>
              <p className="text-on-surface-variant text-sm">All extraction mandates have been reviewed and approved for execution.</p>
            </div>
          </div>
        )}

        {/* Similar Cases Table Card */}
        <div className="glass-card p-8">
          <div className="flex items-center justify-between mb-8">
            <h4 className="font-bold text-on-surface text-xl tracking-tight">Similar Cases & RAG Evidence</h4>
            <button className="text-primary-blue text-[10px] font-bold uppercase tracking-[0.2em] hover:underline flex items-center gap-2">
              Expand Repository <span className="material-symbols-outlined text-sm">open_in_new</span>
            </button>
          </div>
          
          <div className="space-y-1">
            <div className="grid grid-cols-12 gap-4 pb-4 border-b border-outline-variant/20 text-on-surface-variant text-[10px] font-bold uppercase tracking-[0.2em]">
              <div className="col-span-3">Case ID</div>
              <div className="col-span-3">Similarity</div>
              <div className="col-span-2">Outcome</div>
              <div className="col-span-4 text-right sm:text-left">Core Precedent</div>
            </div>
            
            {citations.length > 0 ? citations.map((c: any, i: number) => (
              <CaseRow key={i} id={c.citation_id_raw || c.cited_case_name_raw || '—'} similarity={85 - i * 5} outcome={c.citation_context || '—'} precedent={c.cited_case_name_raw || '—'} />
            )) : (
              <div className="py-8 text-center text-on-surface-variant opacity-50 text-sm">No cited cases found in extraction.</div>
            )}
          </div>
        </div>
      </div>

      {/* Right Column */}
      <div className="xl:col-span-5 h-full">
        <div className="glass-card flex flex-col h-full min-h-[600px] p-8">
          <div className="flex items-center gap-4 mb-10">
            <div className="bg-secondary-container/30 p-2.5 rounded-xl border border-outline-variant/20">
              <span className="material-symbols-outlined text-on-surface-variant">timeline</span>
            </div>
            <h4 className="font-bold text-on-surface text-xl tracking-tight">Approved Compliance Roadmap</h4>
          </div>
          
          <div className="flex-grow">
            {isVerified ? (
              <div className="space-y-6">
                {verifiedActions?.map((action, idx) => (
                  <div key={action.id} className="relative pl-8">
                    {idx !== verifiedActions.length - 1 && (
                      <div className="absolute left-[11px] top-8 bottom-[-24px] w-0.5 bg-outline-variant/20"></div>
                    )}
                    <div className="absolute left-0 top-1.5 w-6 h-6 rounded-full bg-primary-blue flex items-center justify-center shadow-[0_0_10px_rgba(173,198,255,0.4)]">
                      <span className="text-[10px] text-on-primary-blue font-black">{idx + 1}</span>
                    </div>
                    <div className="bg-surface-container-high/40 border border-outline-variant/20 rounded-xl p-4">
                      <div className="flex justify-between items-start mb-2">
                        <div className="space-y-1">
                          <h5 className="font-bold text-on-surface text-sm uppercase tracking-wider">{action.title}</h5>
                        </div>
                        {action.dueDate && (
                          <span className="text-[9px] font-bold text-error-red bg-error-red/10 px-2 py-0.5 rounded uppercase">{action.dueDate}</span>
                        )}
                      </div>
                      <p className="text-xs text-on-surface-variant leading-relaxed">{action.description}</p>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center text-center p-10 bg-surface-container-highest/10 border border-outline-variant/10 rounded-2xl h-full">
                <div className="w-20 h-20 rounded-full bg-surface-container-highest flex items-center justify-center mb-8 border border-outline-variant/20">
                  <span className="material-symbols-outlined text-on-surface-variant text-4xl">route</span>
                </div>
                <p className="text-on-surface font-bold text-2xl tracking-tighter mb-4">No verified actions yet</p>
                <p className="text-on-surface-variant text-base font-medium max-w-[280px] leading-relaxed mx-auto">
                  Please proceed to verification to generate the actionable compliance timeline.
                </p>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

const CaseRow = ({ id, similarity, outcome, precedent }: { id: string, similarity: number, outcome: string, precedent: string }) => (
  <div className="grid grid-cols-12 gap-4 py-5 border-b border-outline-variant/10 items-center hover:bg-white/[0.02] -mx-4 px-4 transition-colors">
    <div className="col-span-3 font-mono font-bold text-on-surface text-base">{id}</div>
    <div className="col-span-3 flex items-center gap-3">
      <div className="flex-grow h-1.5 bg-surface-container-highest rounded-full overflow-hidden">
        <div className="h-full bg-primary-blue transition-all duration-1000" style={{ width: `${similarity}%` }}></div>
      </div>
      <span className="text-xs font-bold text-primary-blue">{similarity}%</span>
    </div>
    <div className={`col-span-2 text-xs font-bold uppercase tracking-widest ${outcome === 'Dismissed' ? 'text-green-400' : 'text-tertiary-container'}`}>
      {outcome}
    </div>
    <div className="col-span-4 flex items-center justify-between gap-4">
      <span className="text-on-surface-variant text-sm font-medium italic truncate">{precedent}</span>
      <button className="material-symbols-outlined text-on-surface-variant hover:text-primary-blue transition-colors text-2xl">article</button>
    </div>
  </div>
);
