# Generated by Django 5.2.13 on 2026-05-05 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(help_text='e.g. writ_appeal, slp, review', max_length=100, unique=True)),
                ('statutory_days', models.IntegerField()),
                ('legal_basis', models.TextField()),
                ('section_reference', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('condonable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.CharField(max_length=20)),
                ('recommendation_reasoning', models.TextField(blank=True)),
                ('compliance_actions', models.JSONField(default=list)),
                ('compliance_deadline', models.DateField(blank=True, help_text='Explicit court-ordered compliance date', null=True)),
                ('compliance_action', models.TextField(blank=True, help_text='What must be done (e.g. pay fine, reinstate employee)')),
                ('statutory_appeal_deadline', models.DateField(blank=True, help_text='Limitation Act deadline for filing appeal', null=True)),
                ('statutory_period_type', models.CharField(blank=True, help_text='e.g. writ_appeal (30d), slp (90d)', max_length=100)),
                ('internal_compliance_deadline', models.DateField(blank=True, null=True)),
                ('internal_appeal_deadline', models.DateField(blank=True, null=True)),
                ('responsible_departments', models.JSONField(default=list)),
                ('ccms_stage', models.CharField(max_length=100)),
                ('similar_cases', models.JSONField(default=list)),
                ('verification_status', models.CharField(default='pending', max_length=20)),
                ('appeal_viability', models.CharField(blank=True, max_length=10)),
                ('appeal_strategy', models.TextField(blank=True)),
                ('appeal_precedents', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('judgment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='action_plan', to='cases.judgment')),
            ],
        ),
        migrations.CreateModel(
            name='CourtCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('court_name', models.CharField(help_text="'Karnataka HC' or 'Supreme Court' etc.", max_length=200)),
                ('is_working_day', models.BooleanField()),
                ('entry_type', models.CharField(blank=True, choices=[('holiday', 'Public Holiday'), ('vacation_start', 'Vacation Start'), ('vacation_end', 'Vacation End'), ('second_saturday', 'Second Saturday')], max_length=30, null=True)),
                ('holiday_reason', models.CharField(blank=True, help_text='e.g. Vijayadashami, Summer Vacation, Sunday', max_length=200)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('date', 'court_name')},
            },
        ),
    ]
