# Generated by Django 5.2.13 on 2026-05-01 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.CharField(max_length=20)),
                ('recommendation_reasoning', models.TextField(blank=True)),
                ('compliance_actions', models.JSONField(default=list)),
                ('legal_deadline', models.DateField(blank=True, null=True)),
                ('internal_deadline', models.DateField(blank=True, null=True)),
                ('responsible_departments', models.JSONField(default=list)),
                ('ccms_stage', models.CharField(max_length=100)),
                ('contempt_risk', models.CharField(max_length=10)),
                ('similar_cases', models.JSONField(default=list)),
                ('verification_status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='action_plan', to='cases.case')),
            ],
        ),
    ]
