# Generated by Django 5.2.14 on 2026-05-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionplan',
            name='full_rag_recommendation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
