# Generated by Django 5.2.13 on 2026-05-14 05:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_plans', '0002_actionplan_full_rag_recommendation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectiveExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('directive_index', models.IntegerField(help_text='Zero-based index into Judgment.court_directions')),
                ('directive_text', models.TextField(blank=True)),
                ('responsible_entity', models.CharField(blank=True, max_length=300)),
                ('action_required', models.TextField(blank=True)),
                ('deadline_mentioned', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='execution_proofs/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='action_plans.actionplan')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['action_plan_id', 'directive_index'],
                'unique_together': {('action_plan', 'directive_index')},
            },
        ),
    ]
