# Generated by Django 5.2.13 on 2026-05-13 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Stable code e.g. HEALTH, PWD, DPAR — never changes', max_length=40, unique=True)),
                ('name', models.CharField(help_text="Display name e.g. 'Health & Family Welfare Department'", max_length=200)),
                ('sector', models.CharField(help_text="Category bucket e.g. 'Health, Environment & Culture'", max_length=120)),
                ('keywords', models.JSONField(default=list, help_text='Lower-case keywords for the dept_classifier')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('head_legal_cell', 'Head of Legal Cell'), ('nodal_officer', 'Nodal Officer'), ('lco', 'Litigation Conducting Officer'), ('principal_secretary', 'Principal Secretary'), ('central_law', 'Central Law Department'), ('state_monitoring', 'State Monitoring Committee'), ('reviewer', 'Reviewer'), ('dept_officer', 'Dept Officer'), ('dept_head', 'Dept Head'), ('legal_advisor', 'Legal Advisor')], default='head_legal_cell', max_length=30),
        ),
        # Cannot cast existing free-text department values to FK.
        # Drop the old CharField column and add the new FK as a fresh column.
        # Existing users' department text is lost (acceptable for demo data).
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='The administrative department this user belongs to. Null for CENTRAL_LAW / STATE_MONITORING roles (global access).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.department'),
        ),
    ]
